config/routes.rb
Ide::Application.routes.draw do
  resources :philes

  match 'jqueryfiletree', to: 'jqueryfiletree#content'
  root :to => 'main#index'
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/jqueryfiletree.rb
class Jqueryfiletree
  
  def initialize(root)
    @root = root
  end

  def get_dirs(path=".")
    path = "" if path.nil?
    @path = File.join(File.expand_path(@root), path)
    @dirs = []
    if File.exists?(@path)
      Dir.entries(@path).each do |dir|
        if File.directory?(File.join(@path, dir)) && dir[0,1]!="."
          @dirs << dir
        end
      end
    end
    @dirs
  end

  def get_files(path=".")
    path = "" if path.nil?
    @path = File.join(File.expand_path(@root), path)
    @files = []
    if File.exists?(@path)
      Dir.entries(@path).each do |file|
        if File.file?(File.join(@path, file))
          @files << file
        end
      end
    end
    @files
  end

  def get_content(path=".")
      [get_dirs(path), get_files(path)]
  end
end

app/models/phile.rb
class Phile < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/jqueryfiletree_controller.rb
class JqueryfiletreeController < ApplicationController
  layout :false
  protect_from_forgery :only => []

  def content
    @parent = params[:dir]
    @dir = Jqueryfiletree.new("#{@parent}").get_content
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
  def index
  	if params[:dir].present?
  	  @dir = params[:dir]
    else
      raise 'wow'
    end
    # @dir = "/Users/dor/src/tikalk/course/korbanot/"
    # @content = File.read("#{@dir}app/controllers/main_controller.rb")
  end
  
end

app/controllers/philes_controller.rb
class PhilesController < ApplicationController
  # GET /philes
  # GET /philes.json
  def index
    @philes = Phile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @philes }
    end
  end

  # GET /philes/1
  # GET /philes/1.json
  def show
    @phile = File.read(params[:id].gsub('DOTDOT','.').gsub('SLASHSLASH','/'))

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: {content: @phile} }
    end
  end

  # GET /philes/new
  # GET /philes/new.json
  def new
    @phile = Phile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @phile }
    end
  end

  # GET /philes/1/edit
  def edit
    @phile = Phile.find(params[:id])
  end

  # POST /philes
  # POST /philes.json
  def create
    @phile = Phile.new(params[:phile])

    respond_to do |format|
      if @phile.save
        format.html { redirect_to @phile, notice: 'Phile was successfully created.' }
        format.json { render json: @phile, status: :created, location: @phile }
      else
        format.html { render action: "new" }
        format.json { render json: @phile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /philes/1
  # PUT /philes/1.json
  def update
    fn = params[:id].gsub('DOTDOT','.').gsub('SLASHSLASH','/')
    File.open(fn,'w+') { |f| 
      f.puts params[:content]
    }
    respond_to do |format|
      format.json { render json: { success: true} }
    end
  end

  # DELETE /philes/1
  # DELETE /philes/1.json
  def destroy
    @phile = Phile.find(params[:id])
    @phile.destroy

    respond_to do |format|
      format.html { redirect_to philes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_helper.rb
module FileHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/philes_helper.rb
module PhilesHelper
end

app/views/jqueryfiletree/content.erb
<ul class="jqueryFileTree" style="display: none;">
  <h5>
  <% @dir[0].each do |dir| %>
    <li class="directory collapsed">
    <a href="#" rel="<%= @parent + dir %>/"><%= dir %></a></li>
  <%end%>
  </h5>
  <% @dir[1].each do |file|%>
    <li class="file ext_<%=File.extname(file)[1..-1]%>"><a href="#" rel="<%=@parent+file %>"><%= file %></a></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ide</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <style>
    html,body {
        height:100%;
    }
      .CodeMirror {
        width: 100%;
      .cm-s-default span.cm-arrow { color: red; }
    </style>

    <meta charset="utf-8">
    <title>Dorke IDE</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->
    <style type="text/css">
      body {
        padding-top: 60px;
      }
    </style>

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
    
    <script type="text/javascript">
        $(document).ready( function() {
            $('#fileTree').fileTree({ root: '<%= @dir %>', script: 'jqueryfiletree' }, function(file) {
              open_file(file)
            });
        });
    </script>
  </head>
  <body>
    <div class="topbar">
      <div class="topbar-inner">
        <div class="container-fluid">
          <a class="brand" href="javascript://">Koko Editor</a>
          <ul class="nav">
            <li><a href="javascript://" class="save_button">Save</a></li>
            <li><a href="javascript://">Find</a></li>
            <li><a href="javascript://">Contact</a></li>
          </ul>
          <!-- <p class="pull-right">Logged in as <a href="#">username</a></p> -->
        </div>
      </div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<div class="container-fluid">
  <div class="sidebar" style="position: fixed; top: 61px" style="overflow: hidden">
    <div class="well">
      <div id="fileTree"></div>
    </div>
  </div>
  <div class="content">
    <div class="hero-unit">
      <form>
        <textarea id="code" name="code"><%= @content %></textarea>
        <br/>
        <!-- <input type="submit" class="btn primary"> -->
      </form>
      <script>
        var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
          lineNumbers: true,
          mode: "text/x-ruby",
          tabMode: "indent",
          matchBrackets: true,
          indentUnit: 4
        });
        $(window).keypress(function(event) {
          if (!(event.which == 115 && event.ctrlKey) && !(event.which == 19)) return true;
          alert("Ctrl-S pressed");
          event.preventDefault();
          return false;
        });
      </script>
    </div>
  </div>
</div>

app/views/philes/_form.html.erb
<%= form_for(@phile) do |f| %>
  <% if @phile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phile.errors.count, "error") %> prohibited this phile from being saved:</h2>

      <ul>
      <% @phile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/philes/edit.html.erb
<h1>Editing phile</h1>

<%= render 'form' %>

<%= link_to 'Show', @phile %> |
<%= link_to 'Back', philes_path %>

app/views/philes/index.html.erb
<h1>Listing philes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @philes.each do |phile| %>
  <tr>
    <td><%= phile.name %></td>
    <td><%= phile.content %></td>
    <td><%= link_to 'Show', phile %></td>
    <td><%= link_to 'Edit', edit_phile_path(phile) %></td>
    <td><%= link_to 'Destroy', phile, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Phile', new_phile_path %>

app/views/philes/new.html.erb
<h1>New phile</h1>

<%= render 'form' %>

<%= link_to 'Back', philes_path %>

app/views/philes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @phile.name %>
</p>

<p>
  <b>Content:</b>
  <%= @phile.content %>
</p>


<%= link_to 'Edit', edit_phile_path(@phile) %> |
<%= link_to 'Back', philes_path %>